FROM alpine:3.9
RUN apk add --no-cache \
    git \
    python3
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pre-commit sample-config > /.pre-commit-config.yaml
ENTRYPOINT ["pre-commit", "run", "--config", "/.pre-commit-config.yaml"]
